disabled_rules:
    - line_length
    - identifier_name

nesting:
    type_level:
        warning: 2

included:
    - Sources/

file_length:
    warning: 1000
    error: 1500

type_body_length:
    warning: 600
    error: 1000

identifier_name:
    min_length:
        warning: 1

reporter: "xcode"
